name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Build the Docker image
      run: docker build --tag python-docker .
    - name: Run docker / app 
      run: docker run -d -p 5000:5000 python-docker
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@0.20.0
